compiler:
- gcc
notifications:
email:
recipients:
- method_aspect_card@yahoo.co.jp
on_success: change #[always|never|change] # default: change
on_failure: change #[always|never|change] # default: always
script: 
- pwd
- ls
- apt-get install ruby1.9.1-dev rubygems1.9.1
- gem install itamae
- itamae local install_recipe.rb

